### ISSUE TITLE
尝试插件功能

### ISSUE THREAD

**Issue by aquarhead** [TeaWhen/Remarque-iOS#3]
通过插件支持各种Remarque-server的各种分类, 如webpac的可以实时查询单册状态

**Comment by xhacker** [comment]
具体？

**Comment by xhacker** [comment]
喔喔就是 server 可以返回一个类似 realtime-detail 的字段？

**Comment by xhacker** [comment]
觉得应该用一个 realtime-url 之类的。这样比较灵活。

**Comment by aquarhead** [comment]
realtime-是什么意思0.0? 我是说(比如)用户装了webpac的插件就会多一个webpac的分类, 而这个分类里面的条目就会有一些扩展信息, 然后app能读取并做相应的显示, 这个分类应该是用户不可控的? 就是必须装对应插件才有对应的分类出来, 这样Remarque能支持更多服务了

**Comment by xhacker** [comment]
改天面基的时候细说~
（得抽空确定一下 Remarque 的需求哈哈）

**Comment by aquarhead** [comment]
好的~
